### ISSUE TITLE
"./utils/concepts.hpp" did not exists

### ISSUE THREAD

**Issue by tiendung** [fengwang/ceras#2]
https://github.com/fengwang/ceras/blob/bcbb4ada346a65ec0d63dd9a540b037985662bd5/include/operation.hpp#L20

**Comment by fengwang** [comment]
Many thanks for pointing this out. I have uploaded this missing header file in the most recent commit https://github.com/fengwang/ceras/commit/967339272d331563c6d441a4f7ed55e65f887919
